import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Profile, ProgramState, SessionPlan } from '../engine/types';
import { fixedRepRange } from '../engine/generator';
import * as C from '../engine/constants';
import { theme, mono } from '../theme';
import { Sheet } from './Sheet';

type StepStatus = 'maxed' | 'today' | 'upcoming';

function fmtRest(sec: number): string {
  return `${Math.floor(sec / 60)}:${(sec % 60).toString().padStart(2, '0')}`;
}

// The fixed-vest progression ladder (reps → sets → rest → load) only applies
// to that engine's heavy day. Every other session falls back to the plain
// why/detail text already generated by the engine.
function useLadderSteps(plan: SessionPlan, state: ProgramState, profile: Profile) {
  const code = plan.decisions[0]?.code;
  const applicable =
    plan.dayKind === 'heavy' &&
    profile.equipment.mode === 'fixed' &&
    ['VEST_FILL_REPS', 'ADD_SET', 'DENSITY_UP', 'SUGGEST_MORE_LOAD'].includes(code ?? '');
  if (!applicable) return null;

  const range = fixedRepRange(profile, state);
  const status = (step: 1 | 2 | 3 | 4): StepStatus => {
    const at: Record<string, number> = {
      VEST_FILL_REPS: 1,
      ADD_SET: 2,
      DENSITY_UP: 3,
      SUGGEST_MORE_LOAD: 4,
    };
    const current = at[code!];
    if (step < current) return 'maxed';
    if (step === current) return 'today';
    return 'upcoming';
  };

  return [
    { n: 1, label: 'Reps', detail: `${range.bottom} → ${range.top} on all sets`, status: status(1) },
    {
      n: 2,
      label: 'Sets',
      detail: `${C.FIXED_BASE_SETS} → ${C.FIXED_MAX_SETS}`,
      status: status(2),
    },
    {
      n: 3,
      label: 'Rest',
      detail: `${fmtRest(C.HEAVY_REST_SEC)} → ${fmtRest(C.FIXED_DENSE_REST_SEC)}`,
      status: status(3),
    },
    {
      n: 4,
      label: 'Load',
      detail: `+${profile.equipment.fixedLoadKg} kg is maxed out`,
      status: status(4),
    },
  ];
}

const BADGE: Record<StepStatus, { label: string; color: string }> = {
  maxed: { label: 'MAXED', color: theme.good },
  today: { label: 'TODAY', color: theme.accent },
  upcoming: { label: 'NEXT', color: theme.textFaint },
};

export function WhySheet({
  visible,
  onClose,
  plan,
  state,
  profile,
}: {
  visible: boolean;
  onClose: () => void;
  plan: SessionPlan;
  state: ProgramState;
  profile: Profile;
}) {
  const steps = useLadderSteps(plan, state, profile);

  return (
    <Sheet visible={visible} onClose={onClose} title={plan.why || 'Why this workout'}>
      {steps ? (
        <>
          <Text style={styles.intro}>
            With a fixed {profile.equipment.fixedLoadKg} kg vest you can't add plates, so the
            engine progresses in a strict order — the way fixed-load athletes actually do it:
          </Text>
          <View style={{ gap: 8, marginTop: 12 }}>
            {steps.map((s) => {
              const badge = BADGE[s.status as StepStatus];
              const isToday = s.status === 'today';
              return (
                <View key={s.n} style={[styles.stepRow, isToday && styles.stepRowToday]}>
                  <View
                    style={[
                      styles.stepDot,
                      s.status === 'maxed' && { backgroundColor: theme.cardMuted },
                      isToday && { backgroundColor: theme.accent },
                    ]}
                  >
                    {s.status === 'maxed' ? (
                      <Text style={[styles.stepDotText, { color: theme.good }]}>✓</Text>
                    ) : (
                      <Text
                        style={[
                          styles.stepDotText,
                          { color: isToday ? theme.onAccent : theme.textDim },
                        ]}
                      >
                        {s.n}
                      </Text>
                    )}
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={[styles.stepLabel, s.status === 'maxed' && { color: theme.textFaint }]}>
                      {s.label}{' '}
                      <Text style={[styles.stepDetail, mono]}>{s.detail}</Text>
                    </Text>
                  </View>
                  <Text style={[styles.badge, { color: badge.color }]}>{badge.label}</Text>
                </View>
              );
            })}
          </View>
          <Text style={styles.footer}>
            Based on double progression as used in published fixed-load calisthenics
            programming — not generated advice.
          </Text>
        </>
      ) : (
        <Text style={styles.intro}>{plan.whyDetail || plan.why}</Text>
      )}
    </Sheet>
  );
}

const styles = StyleSheet.create({
  intro: { fontSize: 13.5, lineHeight: 20.5, color: theme.textDim },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  stepRowToday: { borderColor: theme.accent, borderWidth: 1.5 },
  stepDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.cardMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotText: { fontSize: 12, fontWeight: '700' },
  stepLabel: { fontSize: 13.5, fontWeight: '600', color: theme.text },
  stepDetail: { fontWeight: '400', color: theme.textDim, fontSize: 12.5 },
  badge: { fontSize: 11, fontWeight: '700' },
  footer: { fontSize: 12, lineHeight: 18, color: theme.textFaint, marginTop: 14 },
});
